name: Python Django application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-django  # Instala las dependencias necesarias para flake8 y pytest con Django
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 ./src --max-line-length=79  # Ajusta el path de tu proyecto y las reglas de flake8 si es necesario

    - name: Run Django tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Corre las pruebas de Django usando pytest

    - name: Run Django migrations (si es necesario)
      run: |
        python manage.py migrate --noinput  # Aplica las migraciones de Django antes de ejecutar la app

    - name: Run the Django application (opcional)
      run: |
        python manage.py runserver 0.0.0.0:8000  # Solo si necesitas iniciar el servidor para pruebas u otras acciones
